### ISSUE TITLE
FAILED (remote: image is not a boot image)

### ISSUE THREAD

**Issue by a1exus** [TeamWin/android_device_huawei_angler#1]
I'm following `Fastboot Install Method (No Root Required)` from [TWRP for Huawei Nexus 6P](https://twrp.me/devices/huaweinexus6p.html) and getting following:

```
mbp:~ alexus$ fastboot flash recovery twrp-2.8.7.2-angler.img 
target reported max download size of 494927872 bytes
sending 'recovery' (5 KB)...
OKAY [  0.037s]
writing 'recovery'...
FAILED (remote: image is not a boot image)
finished. total time: 0.059s
mbp:~ alexus$ 
```

please advise.

**Comment by Dees-Troy** [comment]
The recovery image for angler is a lot bigger than 5KB. Invalid download.

**Comment by a1exus** [comment]
Is there an official place to check for md5 checksum?

**Comment by 104012** [comment]
Aahh had the same issue. Used `wget` to fetch the image from the website. Apparently it just downloads the HTML file instead of the image itself.

**Comment by happycherrycake** [comment]
@104012 yes, we only retrieve the real image providing a http referrer header `wget --referer "https://dl.twrp.me/hammerhead/twrp-3.0.2-0-hammerhead.img" https://dl.twrp.me/hammerhead/twrp-3.0.2-0-hammerhead.img`.

@a1exus there are md5sums https://dl.twrp.me/hammerhead/twrp-3.0.2-0-hammerhead.img.md5 etc.
